server:
  tomcat:
    accept-count: 500
    max-threads: 500
    max-connections: 1000
spring:
   data:
      mongodb:
        host: 10.30.137.31
        port: 27017
        username: notify
        password: notify
        database: notify
   rabbitmq:
     host: 10.30.95.85
     port: 6672
     username: avicare
     password: avicare
     virtual-host: avicarecommon
     cache:
       channel:
         size: 5
   redis:
    database: 0
    password: znx1234
    sentinel:
      master: mymaster
      nodes: 10.30.95.85:26379
    pool:
      max-active: -1
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 10000
ccp:
  url: app.cloopen.com
  accountsid: 8aaf070858a8910b0158a8b3a1130022
  accounttoken: 913bc83edd204d7ca206b9de0dcd9b9b
  appid: 8a216da8594f29f80159638d596905fe
  port: 8883
tencent:
  singleurl: https://yun.tim.qq.com/v5/tlssmssvr/sendsms
  massurl: https://yun.tim.qq.com/v5/tlssmssvr/sendmultisms2
  appkey: 9157b3fd59ac7a857fa7b241e91430b7
  sdkappid: 1400034274
  addurl: https://yun.tim.qq.com/v5/tlssmssvr/add_template
  updateurl: https://yun.tim.qq.com/v5/tlssmssvr/mod_template
  getstatusurl: https://yun.tim.qq.com/v5/tlssmssvr/get_template

#启用shutdown #禁用密码验证
endpoints:
  shutdown:
    enabled: true
    sensitive: false
#导出短信相关信息的接口路径
import:
  message:
    url: https://oper.avicare.cn/web-avicare-1.0/message/manage

#爱福客(亿通)企业id
common:
  enterpriseId: 45

#容联短信渠道id
avicare:
  ccp:
   channelId: 5b70ef1614e12f54a4e792f0
  tencent:
   channelId: 5b70f06014e12f54a4e79325

#集团工会总部渠道id
loveAviation:
  login:
    channelId: 5b7fb0c714e12f40dac5fd92

