server:
  tomcat:
    accept-count: 2000
    max-threads: 2000
    max-connections: 2000
  max-http-header-size: 81920
spring:
  rabbitmq:
      host: 10.81.236.103
      port: 6672
      username: avicaremq
      password: iqwueoiruq487509823749827assadf
      virtual-host: avicarecommon
      cache:
        channel:
          size: 5
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  aop:
    auto: true
    proxy-target-class: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zeo43d5733668w2k.mysql.rds.aliyuncs.com/avicare_order?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: zkcxxn_main
    password: 'MsDMqr#0*AHeVbT7'
    initialSize: 5
    minIdle: 1
    maxActive: 20
    maxWait: 6000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    second:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-2zeo43d5733668w2k.mysql.rds.aliyuncs.com/zkcxxn_main?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
      username: zkcxxn_main
      password: 'MsDMqr#0*AHeVbT7'
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 6000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 10.81.10.1:9092
          zkNodes: 10.81.10.1:2181
    bus:
      trace:
        enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
#饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients: file-server
#启用shutdown #禁用密码验证
endpoints:
  shutdown:
    enabled: true
    sensitive: false
#hbase配置
hbase:
  config:
    hbase.zookeeper.quorum: 192.168.192.243
    hbase.zookeeper.property.clientPort: 2181
#es配置
elasticsearch:
  cluster-nodes:
    port: 9300
    ip1: 192.168.192.243
    ip2: 192.168.192.244
    name: avicare
remote:
  url: http://10.50.243.212/web-avicare-1.0







