server:
  tomcat:
    accept-count: 500
    max-threads: 500
    max-connections: 1000

spring:
  data:
    mongodb:
      host: 10.163.144.167
      port: 27017
      username: order
      password: 'order!@#'
      database: order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zeo43d5733668w2k.mysql.rds.aliyuncs.com/avicare_scs?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: zkcxxn_main
    password: 'MsDMqr#0*AHeVbT7'
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 6000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  mvc:
   throw-exception-if-no-handler-found: true
  resources:
   add-mappings: false
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 39.106.248.44:9092
          zkNodes: 39.106.248.44:2181
    bus:
      trace:
        enabled: true
client:
 orderUrl: http://10.50.243.212/web-order-1.0
 coinOrderUrl: http://10.50.243.212/web-coin-1.0
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
#启用shutdown #禁用密码验证
endpoints:
  shutdown:
    enabled: true
    sensitive: false