server:
  tomcat:
    accept-count: 500
    max-threads: 500
    max-connections: 1000

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zeo43d5733668w2k.mysql.rds.aliyuncs.com/avicare_union?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: zkcxxn_main
    password: 'MsDMqr#0*AHeVbT7'
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 6000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  aop:
    auto: true
    proxy-target-class: false
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 10.81.10.1:9092
          zkNodes: 10.81.10.1:2181
    bus:
      trace:
        enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
#启用shutdown #禁用密码验证
endpoints:
  shutdown:
    enabled: true
    sensitive: false