server:
  max-http-header-size: 81920
  tomcat:
    accept-count: 2000
    max-threads: 2000
    max-connections: 2000

spring:
  data:
    mongodb:
      host: 10.163.144.167
      port: 27017
      username: order
      password: 'order!@#'
      database: order
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  aop:
    auto: true
    proxy-target-class: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zeo43d5733668w2k.mysql.rds.aliyuncs.com/avicare_order?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: zkcxxn_main
    password: 'MsDMqr#0*AHeVbT7'
#    url: jdbc:mysql://10.24.163.115/zkcxxn_main?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
#    username: zkcxxn_main
#    password: '#zkcxxn_main#'
    initialSize: 5
    minIdle: 1
    maxActive: 20
    maxWait: 6000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
#    host: 10.29.130.90
#    port: 6379
#    database: 0
#    password: iw29838u23iuaskjdmznmewweo8702
    database: 0
    password: iw29838u23iuaskjdmznmewweo8702
    sentinel:
      master: mymaster
      nodes: 10.29.130.90:26379,10.81.236.103:26379,10.81.11.29:26379
    pool:
      max-active: -1
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 10000
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 10.81.10.1:9092
          zkNodes: 10.81.10.1:2181
    bus:
      trace:
        enabled: true

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#启用shutdown #禁用密码验证
endpoints:
  shutdown:
    enabled: true
    sensitive: false

#外部请求地址
orderclient:
  #福利订单属性
  avicareUrl: http://10.50.243.212/web-avicare-1.0
  #订单url查询物流信息
  webOrderUrl: http://10.50.243.212/web-order-1.0