server:
  max-http-header-size: 81920
  tomcat:
    accept-count: 500
    max-threads: 500
    max-connections: 1000

wechat:
  signature: avicarerun
  uniquecode: gh_e126f48ac29e
#  resource:
#    avicare:
#      appid: wx5593d70b7945662b
#      secret: fdf81eef5b82de66092c2e39112ae6b3

spring:
  data:
    mongodb:
      host: 10.163.144.167
      port: 27017
      username: wechat
      password: 'wechat!@#'
      database: wechat
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
#    host: 10.29.130.90
#    port: 6379
#    database: 9
#    password: iw29838u23iuaskjdmznmewweo8702
    database: 9
    password: iw29838u23iuaskjdmznmewweo8702
    sentinel:
      master: mymaster
      nodes: 10.29.130.90:26379,10.81.236.103:26379,10.81.11.29:26379
    pool:
      max-active: -1
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 10000
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 10.81.10.1:9092
          zkNodes: 10.81.10.1:2181
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 10.81.236.103
    port: 6672
    username: avicaremq
    password: iqwueoiruq487509823749827assadf
    virtual-host: avicarecommon
    cache:
      channel:
        size: 5

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#启用shutdown #禁用密码验证
endpoints:
  shutdown:
    enabled: true
    sensitive: false