server:
  tomcat:
    accept-count: 500
    max-threads: 500
    max-connections: 1000

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zeo43d5733668w2k.mysql.rds.aliyuncs.com/zkcxxn_main?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
    username: zkcxxn_main
    password: 'MsDMqr#0*AHeVbT7'
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 6000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  redis:
#        host: 10.29.130.90
#        port: 6379
#        database: 7
#        password: iw29838u23iuaskjdmznmewweo8702
    database: 7
    password: iw29838u23iuaskjdmznmewweo8702
    sentinel:
      master: mymaster
      nodes: 10.29.130.90:26379,10.81.236.103:26379,10.81.11.29:26379
    pool:
      max-active: -1
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 10000

  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 10.81.10.1:9092
          zkNodes: 10.81.10.1:2181
    bus:
      trace:
        enabled: true


#启用shutdown #禁用密码验证
endpoints:
  shutdown:
    enabled: true
    sensitive: false
  web:
    exposure:
      include: service-registry

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
url:
  brandInfo: http://10.50.243.212/web-avicare-1.0/opr/mall/mdsebrand/queryMdseBrand
  webAvicareDomainName: http://10.50.243.212/web-avicare-1.0
  web-account: https://app.avicare.cn/web-account-1.0
# 商品位置数量限制
activity:
  content:
    maxQuantity: 120
