server:
  tomcat:
    accept-count: 500
    max-threads: 500
    max-connections: 1000
spring:
   data:
      mongodb:
         host: 10.163.144.167
         port: 27017
         username: owner
         password: 'notify!@#'
         database: notify
   rabbitmq:
      host: 10.81.236.103
      port: 6672
      username: avicaremq
      password: iqwueoiruq487509823749827assadf
      virtual-host: avicarecommon
      cache:
         channel:
         size: 5

   redis:
#      host: 10.29.130.90
#      port: 6379
#      database: 9
#      password: iw29838u23iuaskjdmznmewweo8702
      database: 6
      password: iw29838u23iuaskjdmznmewweo8702
      sentinel:
        master: mymaster
        nodes: 10.29.130.90:26379,10.81.236.103:26379,10.81.11.29:26379
      pool:
        max-active: 500
        max-wait: -1
        max-idle: 20
      timeout: 10000
   cloud:
       stream:
         default-binder: kafka
         kafka:
           binder:
             brokers: 10.81.10.1:9092
             zkNodes: 10.81.10.1:2181
       bus:
         trace:
           enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ccp:
  url: app.cloopen.com
  accountsid: 8aaf070858a8910b0158a8b3a1130022
  accounttoken: 913bc83edd204d7ca206b9de0dcd9b9b
  appid: 8a216da8594f29f80159638d596905fe
  port: 8883
tencent:
  singleurl: https://yun.tim.qq.com/v5/tlssmssvr/sendsms
  massurl: https://yun.tim.qq.com/v5/tlssmssvr/sendmultisms2
  appkey: 9157b3fd59ac7a857fa7b241e91430b7
  sdkappid: 1400034274
  addurl: https://yun.tim.qq.com/v5/tlssmssvr/add_template
  updateurl: https://yun.tim.qq.com/v5/tlssmssvr/mod_template
  getstatusurl: https://yun.tim.qq.com/v5/tlssmssvr/get_template

#启用shutdown #禁用密码验证
endpoints:
  shutdown:
    enabled: true
    sensitive: false

#导出短信相关信息的接口路径
import:
   message:
     url: https://oper.avicare.cn/web-avicare-1.0/message/manage

#爱福客(亿通)企业id
common:
  enterpriseId: 45

#容联短信渠道id
avicare:
  ccp:
   channelId: 5b3e4ed5dab51867ef10eeae
  tencent:
   channelId: 5b7f8971dab518773edb3efe

#集团工会总部渠道id
loveAviation:
  login:
    channelId: 5b3ec38fdab51867ef11b276

