spring:
  sleuth:
    enabled: false
    sampler:
      percentage: 1.0
  cloud:
    stream:
      kafka:
        binder:
          brokers: 10.81.8.124:9092
          zkNodes: 10.81.8.124:2181
#          brokers: 127.0.0.1:9092
#          zkNodes: 127.0.0.1:2181
zipkin:
  storage:
    type: elasticsearch
    StorageComponent: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      max-requests: 30
      index: zipkin
      index-shards: 3
      index-replicas: 1
      hosts: 10.81.8.124:9200
#      hosts: 127.0.0.1:9200

#启用shutdown #禁用密码验证
endpoints:
  shutdown:
    enabled: true
    sensitive: false