server:
  tomcat:
    accept-count: 500
    max-threads: 500
    max-connections: 1000

recharge:
  template:
    url: https://mycdn.avicare.cn/group1/M00/00/02/ChpU11riwYeAWKloAAAnVfxxrvc72.xlsx

sms:
  template: 245604
spring:
  http:
    multipart:
      enabled: true
      location: /usr/avicare/data/cache
      max-file-size: 10MB
  redisson:
    config:
      codec:
        className: org.redisson.codec.KryoCodec
      sentinelServersConfig:
        masterName: mymaster
        sentinelAddresses: redis://10.30.95.85:26379
        password: znx1234
        clientName: cardAccountRedission
#      singleServerConfig:
#        address: redis://127.0.0.1:6379
#        password: znx1234
#        clientName: cardAccountRedission
  rabbitmq:
      host: 10.30.95.85
      port: 6672
      username: avicare
      password: avicare
      virtual-host: avicarecommon
      cache:
        channel:
          size: 5
  data:
    solr:
      host: http://10.30.137.31:8983/solr
      cuscore:
        camanagemdse: camanagemdse
        mdse: mdse
      zk-host:
      import-host: http://10.30.137.31:8983/solr
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.66.88.69:3306/zkcxxn_main?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
    username: avicare
    password: avicare201802
    initialSize: 5
    minIdle: 5
    maxActive: 200
    maxWait: 6000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    database: 0
    password: znx1234
    sentinel:
      master: mymaster
      nodes: 10.30.95.85:26379
    pool:
      max-active: -1
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 10000
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 123.56.4.251:9092
          zkNodes: 10.66.176.209:2181
    bus:
      trace:
        enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#启用shutdown #禁用密码验证
endpoints:
  shutdown:
    enabled: true
    sensitive: false

url:
  card-account:
    remote-sku-category: http://10.66.176.209:8080/web-avicare-1.0
    remote-account: http://10.66.176.209:18080/web-account-1.0

logging:
  level:
    com:
      sc:
        dao: debug