server:
  tomcat:
    accept-count: 500
    max-threads: 500
    max-connections: 1000

#token配置
account:
  uri:
    #    wxUrl: https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxf20290f567b56089&redirect_uri=replace&response_type=code&scope=snsapi_base&state=h5mall#wechat_redirect
    #    qrcodeUrl: https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket=
    remoteNoticeUrl: http://127.0.0.1:8080/web-coin-1.0/v1/tember/updatetembernotice.share
    fileUploadUrl: http://127.0.0.1:10080
    syncSupplierUrl: http://127.0.0.1:8080/web-avicare-1.0/opr/mall/mdsesupplier/addsupplier/
    employeeTemplateUrl: https://mycdn.avicare.cn/group1/M00/06/38/Chvbolriu5uAVz2fAAAmoRz7vSs35.xlsx
    remoteUpdateMerchandiseStatusUrl: https://dev.avicare.cn/web-avicare-1.0/opr/mall/mdse/remoteUpdateMdseStatus
    remoteUpdateCardAccountMdseStatus: https://dev.avicare.cn/apirest/rest-card-account/card/account/mdse/updateCardAccountMdseStatus
  excel:
    benefit:
      普通: B1
      中级: B2
      高级: B3
    payGrade:
      2500以下: P1
      2500-4999: P2
      5000-7499: P3
      7500-9999: P4
      10000-14999: P5
      15000-19999: P6
      20000-24999: P7
      25000-29999: P8
      30000以上: P9
    bankDeposit:
      工商银行: 100000001804
      招商银行: 100000001805
      中国银行: 100000001806
      建设银行: 100000001807
      交通银行: 100000001808
      农业银行: 100000001809
      广东发展银行: 100000001810
      深圳发展银行: 100000001811
      浦发银行: 100000001812
      泰隆商业银行: 100000001813
      中信银行: 100000001814
      华夏银行: 100000001815
      光大银行: 100000001816
      北京银行: 100000001817
      民生银行: 100000001834
      邮政储蓄银行: 100000001829

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: avicare
    password: avicare
    virtual-host: avicarecommon
    cache:
      channel:
        size: 5
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  aop:
    auto: true
    proxy-target-class: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zkcxxn_main?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: avicare
    password: avicare201802
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 6000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    second:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/avicare_market?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
      username: avicare
      password: avicare201802
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 6000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    #    host: 127.0.0.1
    #    port: 6379
    database: 0
    password: 123456
    sentinel:
      master: master
      nodes: 192.168.0.102:26379
    pool:
      max-active: -1
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 10000
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 192.168.0.102:9092
          zkNodes: 192.168.0.102:2181
    bus:
      trace:
        enabled: true

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients: file-server

third:
  platform:
    resource:
      wrdc20180112:
        innerEnterpriseID: 756cf85163994656b05a344338ecdbeb
        secretKey: Yunjia2018_Shop!
      huasheng20180112:
        innerChannelID: 31df8fd14b854e61889c02c49a7fc094
        secretKey: LmMGStGtOpF4xNyvYt54EQ==
        remoteUrl: http://www.huashengshenghuo.com/api/index.php?act=companytest

avicare:
  password:
    rules: TG1NR1N0R3RPcEY0eE55dll0NTRFUT09

#启用shutdown #禁用密码验证
endpoints:
  shutdown:
    enabled: true
    sensitive: false

enterprise:
  constant:
    yt: 45
#  正式
#  b4600024630d44969980717e6d9ceea5