server:
  tomcat:
    accept-count: 500
    max-threads: 500
    max-connections: 1000

spring:
  redisson:
    config:
      codec:
        className: org.redisson.codec.KryoCodec
      sentinelServersConfig:
        masterName: mymaster
        sentinelAddresses: redis://10.30.95.85:27500
        password: znx1234
        clientName: activityRedission
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  aop:
    auto: true
    proxy-target-class: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/avicare_union?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: avicare_pre
    password: avicarepre
#     url: jdbc:mysql://47.95.33.180/zkcxxn_main?characterEncoding=UTF-8&autoReconnect=true&useSSL=true
#     username: zkcxxn_main
#     password: zkcxxn_main#
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 6000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    database: 3
    password: znx1234
    sentinel:
      master: mymaster
      nodes: 10.30.95.85:27500
    pool:
      max-active: -1
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 10000
  cloud:
      stream:
        default-binder: kafka
        kafka:
          binder:
#            brokers: 39.106.248.44:9092
#            zkNodes: 39.106.248.44:2181
            brokers: 182.92.124.111:9092
          zkNodes: 10.66.176.48:2181
      bus:
        trace:
          enabled: true

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
#启用shutdown #禁用密码验证
endpoints:
  shutdown:
    enabled: true
    sensitive: false
##活动分享相关
wechat:
  clientId: gh_01eeda3f3d41
  appId: wxf20290f567b56089
  appSecret: f8cc6dc45cf7cbb7dae48b0da90ca6e4
  share:
    url:
      votetext: https://test.avicare.cn/web-wechat/shop/dist/#/activityshare/votetext
      voteimg: https://test.avicare.cn/web-wechat/shop/dist/#/activityshare/voteimg
      voteDetail: https://test.avicare.cn/web-wechat/shop/dist/#/activityshare/voteDetail
      bookDetail: https://test.avicare.cn/web-wechat/shop/dist/#/activityshare/activitybookdetail
#图书活动相关
isbn:
  oneAppkey: 9fa4e9e9a61405ef
  twoAppkey: 3d8a7fb64748a5e3
  url: https://api.jisuapi.com/isbn/query